server:
  port: 8889

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'

zuul:
  routes:
    data-center:
      path: /data/**
      url: http://localhost:8801/data
    data-definition:
      path: /datadefinitions/**
      url: http://localhost:8802/data-definitions
    developer:
      path: /developers/**
      url: http://localhost:8804/developers
    device-definition:
      path: /devicedefinitions/**
      url: http://localhost:8805/device-definitions
    device-center:
      path: /devices/**
      url: http://localhost:8806/devices
    file:
      path: /files/**
      url: http://localhost:8807/files
    user:
      path: /users/**
      url: http://localhost:8809/users
    report:
      path: /reports/**
      url: http://localhost:8811/reports

developer:
  service:
    uri: http://localhost:8804/developers/

auth:
  ignored:
    rules:
      - host: www.umasuo.com
        path: ^(/auth/anonymous)
        method: GET
      - host: localhost
        path: ^(/developers/signin)[a-z0-9\-/]*
        method: POST